/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveBar: typeof import('./src/components/active-bar.vue')['default']
    BasicEditor: typeof import('./src/views/basic-editor.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    FormEditor: typeof import('./src/views/formEditor.vue')['default']
    FormList: typeof import('./src/components/form-list.vue')['default']
    FormTip: typeof import('./src/components/form-tip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg/svgIcon.vue')['default']
    ToolBar: typeof import('./src/components/tool-bar.vue')['default']
  }
}
